name: capserv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - fastapi==0.118.0
      - greenlet==3.2.4
      - groq==0.32.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - iniconfig==2.1.0
      - jiter==0.11.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-core==0.3.78
      - langchain-groq==0.3.8
      - langchain-openai==0.3.34
      - langchain-text-splitters==0.3.11
      - langgraph==0.6.8
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.32
      - openai==2.1.0
      - orjson==3.11.3
      - ormsgpack==1.10.0
      - packaging==25.0
      - pluggy==1.6.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - starlette==0.48.0
      - tenacity==9.1.2
      - tiktoken==0.11.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - xxhash==3.6.0
      - zstandard==0.25.0
